# Creating 1D and 2D arrays 

In [5]:
# Referencing the youtube video https://www.youtube.com/watch?v=QUT1VHiLmmI&ab_channel=freeCodeCamp.org

import numpy as np

numbers=[1,2,3,4,5]
numbers=np.array(numbers)
print('One dimensional array', numbers)


One dimensional array [1 2 3 4 5]


In [8]:
numbers=[1,2,3,4,5],["hello","learners"]
numbers=np.array(numbers,dtype=object)
print(numbers)

[list([1, 2, 3, 4, 5]) list(['hello', 'learners'])]


In [10]:
eyeMat=np.eye(3)
print(eyeMat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
randomInt=np.random.randint(1,100,10)
print(randomInt)

[69 33 42 79 16 61 45 24 78 74]


In [21]:
names=np.array(['john','mathew','simon'])
print('Last element of the array is',names[-1])
print('Reversed : ',names[::-1])

Last element of the array is simon
Reversed :  ['simon' 'mathew' 'john']


In [22]:
numbers=np.array([[5,8,3],[3,1,2],[5,7,8]])
print('Second Row, thrid element : ', numbers[1,2])

Second Row, thrid element :  2


In [24]:
numbers= np.arange(1,26).reshape(5,5)
print("Numbers in 5X5 matrix form ",numbers)

Numbers in 5X5 matrix form  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# The Basics 
 #https://youtu.be/QUT1VHiLmmI

In [33]:
#One dimentional array 
a=np.array([1,2,3,4,5,6])
print(a)

# Two dimentional array

b=np.array([[1,2,3,4],[2,3,4,5]])
print(b)

#dimention of array
a.ndim

#Shape 
b.shape

#type
a.dtype

#size
a.itemsize

#total size
a.nbytes

[1 2 3 4 5 6]
[[1 2 3 4]
 [2 3 4 5]]


48

In [51]:

a=np.array([[1,2,3,4,5,6,7,8],[5,6,7,8,9,0,4,5]])
print(a)



#Specific element at specified row and column
a[0,2]

#Specific row 
a[0, : ]

#Specific Column 
a[:,1]

#alternative way to access
a[0,1:-1:2]


[[1 2 3 4 5 6 7 8]
 [5 6 7 8 9 0 4 5]]


array([2, 4, 6])

In [52]:
#modifying 

print(a)
a[1,5]=50
print(a)

[[1 2 3 4 5 6 7 8]
 [5 6 7 8 9 0 4 5]]
[[ 1  2  3  4  5  6  7  8]
 [ 5  6  7  8  9 50  4  5]]


In [55]:

#Different ways to create arrays 

#array of zeros
a=np.zeros(10)
print(a)

#array of zeros
a=np.ones(10)
print(a)

#array of zeros
a=np.random.random(10)
print(a)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.0284944  0.01990206 0.52063563 0.75885924 0.17506724 0.75226264
 0.91740557 0.7582443  0.04577546 0.48811069]


In [58]:
shape=a.shape
print(shape)

(10,)


In [60]:
dim=a.ndim
print(dim)

1


In [61]:
a=np.full((2,3,4),9)
print(a)


[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [64]:
a=np.arange(0,1000,4)
print(a)

[  0   4   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68
  72  76  80  84  88  92  96 100 104 108 112 116 120 124 128 132 136 140
 144 148 152 156 160 164 168 172 176 180 184 188 192 196 200 204 208 212
 216 220 224 228 232 236 240 244 248 252 256 260 264 268 272 276 280 284
 288 292 296 300 304 308 312 316 320 324 328 332 336 340 344 348 352 356
 360 364 368 372 376 380 384 388 392 396 400 404 408 412 416 420 424 428
 432 436 440 444 448 452 456 460 464 468 472 476 480 484 488 492 496 500
 504 508 512 516 520 524 528 532 536 540 544 548 552 556 560 564 568 572
 576 580 584 588 592 596 600 604 608 612 616 620 624 628 632 636 640 644
 648 652 656 660 664 668 672 676 680 684 688 692 696 700 704 708 712 716
 720 724 728 732 736 740 744 748 752 756 760 764 768 772 776 780 784 788
 792 796 800 804 808 812 816 820 824 828 832 836 840 844 848 852 856 860
 864 868 872 876 880 884 888 892 896 900 904 908 912 916 920 924 928 932
 936 940 944 948 952 956 960 964 968 972 976 980 98

In [65]:
a=np.linspace(0,1000,1001)
print(a)

[   0.    1.    2. ...  998.  999. 1000.]
